name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  DOCKER_BUILDKIT: 1
  DOCKER_BUILDKIT_INLINE_CACHE: 1
  DOCKER_IMAGE_NAME: skriptfabrik/json-schema-bundler
  NODE_VERSION: 18.2.0

jobs:
  publish-push:
    name: Publish package and Push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Bump package version
        if: github.ref_type == 'tag'
        run: npm version from-git --no-git-tag-version

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        if: github.ref_type == 'tag'
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push latest Docker image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v2
        with:
          build-args: |-
            BUILDKIT_INLINE_CACHE=${{ env.DOCKER_BUILDKIT_INLINE_CACHE }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:latest
          platforms: |-
            linux/amd64
            linux/arm64
          pull: true
          push: true
          tags: |-
            ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Build and Push Docker image
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v2
        with:
          build-args: |-
            BUILDKIT_INLINE_CACHE=${{ env.DOCKER_BUILDKIT_INLINE_CACHE }}
            JSON_SCHEMA_BUNDLER_VERSION=v${{ env.GITHUB_REF_NAME }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:latest
          platforms: |-
            linux/amd64
            linux/arm64
          pull: true
          push: true
          tags: |-
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }}
